#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx commitlint --config .commitlintrc.ts --edit $1 ||
(
    echo '❌ Commit message format is incorrect. Please follow the conventional commit format.';
    false;
)